language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"

sudo: false
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"

addons:
  apt:
    packages:
      - libdb-dev
      - graphviz
      - libgd2-xpm-dev
      - libxml2-dev

before_install:
  - "cpanm Devel::Cover::Report::Coveralls"
  - "cpanm DBD::SQLite"

script:
  - "perl Build.PL && ./Build build && cover -test -report coveralls"
