language: perl
    perl:
      - "5.24"
      - "5.22"
      - "5.20"
    before_install:
      cpanm -n Devel::Cover::Report::Coveralls
    script:
      perl Build.PL && ./Build build && cover -test -report coveralls
